title: Camospecs' Blog
author: Camospecs
remote_theme: jekyll/minima
minima:
  skin: dark

permalink: /:title.html

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/camospecs" }
