title: Camospecs' Blog
author: Camospecs
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/camospecs" }
    - { platform: x,  user_url: "https://x.com" }

description: >
  A digital collection of projects I've attempted and anything else I think worthy of 
  note.

header_pages:
  - useful-links.md
  

permalink: /:title.html

